adding installation  from netlify to generate allure reports

diff --git a/.github/workflows/playwright_with AllureReports.yml b/.github/workflows/playwright_with AllureReports.yml
--- a/.github/workflows/playwright_with AllureReports.yml
+++ b/.github/workflows/playwright_with AllureReports.yml
@@ -6,7 +6,7 @@ on:
     branches: [ main]
 jobs:
   test:
-    timeout-minutes: 60
+    #timeout-minutes: 60
     runs-on: ubuntu-latest
     steps:
     - name: Checkout code to repository
@@ -17,12 +17,27 @@ jobs:
         node-version: lts/*
     - name: Install dependencies
       run: npm ci
+
+    - name: Cache Playwright browsers
+      uses: actions/cache@v3
+      id: playwright-cache
+      with:  
+        key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
+        path: ~/.cache/ms-playwright
+
     - name: Install Playwright Browsers
+      if: steps.playwright-cache.outputs.cache-hit != 'true'
       run: npx playwright install --with-deps
 
     - name: Run Playwright tests tests/getcall.spec.js
       run: npx playwright test tests/getcall.spec.js
       continue-on-error: true
+
+    - name: Install Java (required for Allure report generation)
+      uses: actions/setup-java@v4
+      with:
+        distribution: 'temurin'
+        java-version: '17'  
       
     #- uses: actions/upload-artifact@v4
     #  if: ${{ !cancelled() }}
@@ -32,12 +47,18 @@ jobs:
     #    retention-days: 30
 
     # Install Allure Commandline and Allure Playwright adapter
-    #- name: Install Allure Commandline
-    #  run: npm install -g  --save-dev allure-commandline
+    - name: Install Allure Commandline CLI globally
+      #  run: npm install -g  --save-dev allure-commandline
+      run: |
+        npm install -g allure-commandline
+        echo "$(npm root -g)/./bin/allure"  >> $GITHUB_PATH
+        echo "/user/local/bin/allure"  >> $GITHUB_PATH
+        allure --version
     #- name: Allure Playwright adapter
     #  run: npm install -D --save-dev allure-playwright
 
     - name: Generate Allure report
+      if: success() || failure()  # Generate report even if tests fail
       run: npx allure generate allure-results --clean --o allure-report
 
     - name: Upload Allure report as artifact  
@@ -50,6 +71,13 @@ jobs:
     # Tests run automatically on pushes and pull requests
     # Allure report is generated after execution
     # Allure report is uploaded as an artifact for later download and analysis
-    - name: CDeploy Allure report to Netlify    
+
+    - name: Deploy Allure report to Netlify    
       if: ${{ always() }}      
-      run: npx netlify deploy --dir=allure-report --prod --message="Allure report deployed from GitHub Actions"
+      run: |
+        npx netlify deploy \
+        --site ${{ secrets.NETLIFY_SITE_ID }} \
+        --prod \
+        --dir allure-report
+      env:
+        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}   
